WebApplication2/Controllers/InviteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class InviteController : Controller
    {
        // GET: Invite
        public ActionResult Index()
        {
            return View("InviteGuest");
        }
        [HttpPost]

        public ActionResult InviteGuest(InviteModel model)
        {
            if (ModelState.IsValid)
            {
             SendEmail (model);
             return View("Thanks", model);
            }
                
               
           else
            return View("InviteGuest", model);
        }

        private void SendEmail(InviteModel mailModel)
        {
            var smtpClient = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                UseDefaultCredentials = true,
                Credentials = new NetworkCredential("gym550182@gmail.com", "!QAZ2wsx#EDC")
            };

            var mailMessage = new MailMessage
            {
                Sender= new MailAddress("gym550182@gmail.com"), 
                From= new MailAddress("gym550182@gmail.com"),
                To = { mailModel.Email}, 
                Body= "tresc maila", 
                IsBodyHtml= true

            };

           smtpClient.Send(mailMessage);

        }
        

    }
}

WebApplication2/Views/Invite/InviteGuest.cshtml
@model WebApplication2.Models.InviteModel

@{
    ViewBag.Title = "InviteGuest";
}

<h2>InviteGuest</h2>


@using (Html.BeginForm("InviteGuest", "Invite", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>InviteModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WillAttend, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.WillAttend, new[]
           {
               new SelectListItem { Text= "Tak, przyjdę", Value=bool.TrueString},
               new SelectListItem {Text="Nie, nie przyjdę", Value=bool.FalseString }

           }, "Wybierz opcję", new  {@class= "fore-control"})


                @*//@Html.EditorFor(model => model.WillAttend, new { htmlAttributes = new { @class = "form-control" } })
                //@Html.ValidationMessageFor(model => model.WillAttend, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication2/Views/Invite/Thanks.cshtml
@model WebApplication2.Models.InviteModel
@{
    ViewBag.Title = "Thanks";
}


<h1>Dziękujemy, @Model.Name @Model.Surname !</h1>
@if (Model.WillAttend == true)
{
    @:Cieszymy się, że przyjedziesz do nas. Napoje są juz w lodówce!
}
else
{
    @:Przykro mi, że nie możesz się zjawić, ale dziękujemy za informacje!

}