WebApplication2/Controllers/BMIController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.BuissnessLogic;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class BMIController : Controller
    {

        private BMILogic _bmiLogic;


        public BMIController()
        {
            _bmiLogic = new BMILogic();
        }

        // GET: BMI
        public ActionResult BMIChecker()
        {
            return View();
        }
        [HttpPost]

        public ActionResult BMIChecker2(BmiModel model)
        {


            if (ModelState.IsValid)
            {
                var wynik = _bmiLogic.CheckBMIValue(model);


                if (wynik < 18.5)
                {
                    ViewBag.Dane = "Masz niedowagę";

                }
                else if (wynik < 18.6 && wynik > 24.99)
                {
                    ViewBag.Dane = "Twoja waga jest prawidłowa!";
                }

                else if (wynik > 25)
                {
                    ViewBag.Dane = "Masz nadwage!";
                }

            };

            return View("BMIChecker", model);
        }


    }
}

WebApplication2/Views/BMI/BMIChecker.cshtml
@model WebApplication2.Models.BmiModel

@{
    ViewBag.Title = "BMIChecker";
}

<h2>BMIChecker</h2>

@using (Html.BeginForm("BMIChecker2", "BMI", FormMethod.Post, new { @class = "form-horizontal" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BmiModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MyWeight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MyWeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MyWeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MyHeight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MyHeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MyHeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MyGender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.MyGender, new[]
           {
               new SelectListItem { Text= "Kobieta", Value=bool.TrueString},
               new SelectListItem {Text="Mężczyzna", Value=bool.FalseString }

           }, "Wybierz opcję", new { @class = "fore-control" })


                @*//@Html.EditorFor(model => model.WillAttend, new { htmlAttributes = new { @class = "form-control" } })
            //@Html.ValidationMessageFor(model => model.WillAttend, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@ViewBag.Dane
<div>
    @Html.ActionLink("Back to List", "Index")
</div>